### PR TITLE
add roles only feature / requested by WPB

### PR DESCRIPTION
**Pull request by bhatikuldeep**

### CODE REVIEW

**Review by srb3 — COMMENTED** [review]
Looks ok to me, but will let Avik approve, did you test updating an existing tenant release user role with the remove roles flag, and then updating the groups to see if it all worked as expected?

**Review by avik-sengupta-kong — COMMENTED** [review]
@bhatikuldeep can I suggest the following?
Rename groups-and-roles.yaml with groups-and-roles_anchor.yaml/groups-and-roles_wpb.yaml. 
Rename old-groups-and-roles.yaml with groups-and-roles.yaml/groups-and-roles_wsit.yaml. 
Update readme with the new option, add example ( same as groups with workspace) and also worth mentioning to rename the groups-and-roles.yaml when running on the local.

If you have not already, suggest following manual tests.
1. Test applying roles with existing workspace.
2. Test applying roles with non-existing workspace(ignored)
3. Wipe Worksapce (since you have changed the index position of this command, just to be safe).

**Comment by bhatikuldeep** [comment]
> Looks ok to me, but will let Avik approve, did you test updating an existing tenant release user role with the remove roles flag, and then updating the groups to see if it all worked as expected?

@srb3 tested this scenario, works as expected.

**Comment by bhatikuldeep** [comment]
> @bhatikuldeep can I suggest the following? Rename groups-and-roles.yaml with groups-and-roles_anchor.yaml/groups-and-roles_wpb.yaml. Rename old-groups-and-roles.yaml with groups-and-roles.yaml/groups-and-roles_wsit.yaml. Update readme with the new option, add example ( same as groups with workspace) and also worth mentioning to rename the groups-and-roles.yaml when running on the local.
> 
> If you have not already, suggest following manual tests.
> 
> 1. Test applying roles with existing workspace.
> 2. Test applying roles with non-existing workspace(ignored)
> 3. Wipe Worksapce (since you have changed the index position of this command, just to be safe).

@avik-sengupta-kong all tested and file name corrected, can you approve PR?

**Review by avik-sengupta-kong — APPROVED** [review]

**Pull request merged**
